### ISSUE TITLE
Add panel for PiHole

### ISSUE THREAD

**Issue by jrg89** [jrg89/homeassistant-config#3]
```yaml
panel_iframe:
  pihole:
    title: 'PiHole'
    icon: mdi:chart-pie
    url: !secret PIHOLE_URL
```
